# Generated by Django 2.0.3 on 2018-05-18 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_auto_20180518_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='party_number',
            new_name='code_number',
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='area',
            new_name='human',
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='introduction',
            new_name='information',
        ),
    ]
